name: StellarSDK CI

on:
  push:
    branches:
      - main
      - 'v*.[0-9]'
  pull_request:

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['22.3', '23.3']
        elixir: ['1.10', '1.11']
    env:
      MIX_ENV: test
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - uses: erlef/setup-elixir@8a52153811d9049cdfa73a1f387e21b604267bea
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - uses: actions/cache@9df7d7c016256c51d661e5d26a8632ccd0581680
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - name: Install Dependencies
        run: |
          rm -rf deps _build
          mix deps.get
      - name: Check Formatting
        run: mix format --check-formatted
      - name: Run Tests
        run: mix test
      - name: Run Credo
        run: mix credo --strict
      # - name: Run Excoveralls
      #   run: mix coveralls.github
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
